server:
  port: 4002


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: APP-SERVICE
          uri: lb://APP-SERVICE
          predicates:
            - Path=/app/**
